name: .NET CI - Cybersecurity Awareness Chatbot

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the CI pipeline

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'  # Specify the .NET version you are using

      # Step 3: Restore dependencies (NuGet packages)
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build the project
        run: dotnet build --configuration Release

      # Step 5: Run tests
      - name: Run tests
        run: dotnet test --configuration Release

      # Step 6: Publish the application (Optional - depends on your project needs)
      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish

      # Step 7: Upload build artifacts (Optional, if you want to store build results)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish
